stages:
  load_data:
    cmd: python src/stage_01_load_save.py --config=config/config.yaml
    deps:
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - artifacts/raw_local_dir/data.csv

  split_and_save_data:
    cmd: python src/stage_02_split_data.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_02_split_data.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/raw_local_dir/data.csv
    params:
      - base.random_state
      - base.split_ratio
    outs:
      - artifacts/split_data_dir/train.csv 
      - artifacts/split_data_dir/test.csv
  
  train_and_save_model:
    cmd: python src/stage_03_train.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_03_train.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/split_data_dir/train.csv
    params:
      - model_params.ElasticNet.alpha
      - model_params.ElasticNet.l1_ratio
      - base.random_state
    outs:
      - artifacts/model/elasticNet.model

  evaluate_metrics: 
    cmd: python src/stage_04_evaluate.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_04_evaluate.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/split_data_dir/test.csv
      - artifacts/model/elasticNet.model
    outs:
      - artifacts/scores_dir/score.json
